# Generated by Django 5.1.2 on 2024-10-14 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('file', models.FileField(upload_to='uploads/documents/', verbose_name='file')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
            },
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('file', models.ImageField(upload_to='uploads/images/', verbose_name='file')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
        migrations.CreateModel(
            name='NewsletterEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='title')),
                ('content', models.TextField(blank=True, null=True, verbose_name='title')),
                ('body', models.TextField(blank=True, null=True, verbose_name='body')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sended', 'Enviado'), ('failed', 'Falló')], default='pending', max_length=10, verbose_name='status')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='send at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('attached_documents', models.ManyToManyField(blank=True, to='email_sends.documentupload')),
                ('attached_images', models.ManyToManyField(blank=True, to='email_sends.imageupload')),
                ('newsletter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsletters.newsletter')),
                ('subscribers', models.ManyToManyField(blank=True, to='newsletters.subscriber')),
            ],
            options={
                'verbose_name': 'newsletter email',
                'verbose_name_plural': 'newsletter emails',
            },
        ),
    ]
