# Generated by Django 5.1.2 on 2024-10-14 19:20

import django.db.models.deletion
import email_sends.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sends', '0001_initial'),
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentupload',
            name='file',
            field=models.FileField(upload_to='uploads/documents/', validators=[email_sends.models.validate_document_file_type], verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='file',
            field=models.ImageField(upload_to='uploads/images/', validators=[email_sends.models.validate_image_file_type], verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='newsletteremail',
            name='attached_documents',
            field=models.ManyToManyField(blank=True, related_name='newsletter_emails', to='email_sends.documentupload'),
        ),
        migrations.AlterField(
            model_name='newsletteremail',
            name='attached_images',
            field=models.ManyToManyField(blank=True, related_name='newsletter_emails', to='email_sends.imageupload'),
        ),
        migrations.AlterField(
            model_name='newsletteremail',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='newsletteremail',
            name='newsletter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_emails', to='newsletters.newsletter'),
        ),
        migrations.AlterField(
            model_name='newsletteremail',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='newsletter_emails', to='newsletters.subscriber'),
        ),
    ]
